vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|10 Mar 2014 21:30:33 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|PBM04\\EPAREDES
vti_modifiedby:SR|SERVER003\\Administrator
vti_timecreated:TR|17 Oct 2007 19:49:19 -0000
vti_timelastindexed:TW|10 Mar 2014 21:30:33 -0000
vti_backlinkinfo:VX|
vti_cacheddtm:TX|10 Mar 2014 21:30:33 -0000
vti_filesize:IR|6835
vti_cachedbodystyle:SR|<BODY ONLOAD="document.frmGral.LOGIN.focus()" scroll=no ONUNLOAD="<%Session("glAutorizacion")=""%>" topmargin="0" leftmargin="2" rightmargin="0" bottommargin="0" background="../../images/bg.gif">
vti_cachedlinkinfo:VX|Q|X001Z900.css S|../../images/bg.gif S|../images/bg.gif S|../images/px1.gif S|../images/bg_left.gif S|../Images/bg_left.gif S|../images/px1.gif S|../images/px1.gif A|X001Z010S.asp S|images/acceso.gif A|adm/admc.asp S|../images/bg_right.gif S|../images/bg_right.gif S|../images/bg.gif S|../images/px1.gif H|http://www.bmasca.com
vti_cachedsvcrellinks:VX|FQUS|X001Z900.css NSUS|file:///D:/SRC/P124/images/bg.gif NSUS|file:///D:/SRC/P124/InsysWeb/images/bg.gif NSUS|file:///D:/SRC/P124/InsysWeb/images/px1.gif NSUS|file:///D:/SRC/P124/InsysWeb/images/bg_left.gif NSUS|file:///D:/SRC/P124/InsysWeb/Images/bg_left.gif NSUS|file:///D:/SRC/P124/InsysWeb/images/px1.gif NSUS|file:///D:/SRC/P124/InsysWeb/images/px1.gif FAUS|X001Z010S.asp FSUS|images/acceso.gif FAUS|adm/admc.asp NSUS|file:///D:/SRC/P124/InsysWeb/images/bg_right.gif NSUS|file:///D:/SRC/P124/InsysWeb/images/bg_right.gif NSUS|file:///D:/SRC/P124/InsysWeb/images/bg.gif NSUS|file:///D:/SRC/P124/InsysWeb/images/px1.gif NHHS|http://www.bmasca.com
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
