vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|19 Nov 2014 16:03:57 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|PBM04\\EPAREDES
vti_modifiedby:SR|SERVER003\\Administrator
vti_timecreated:TR|21 May 2008 20:30:35 -0000
vti_title:SR|.:Web Site - :.
vti_timelastindexed:TW|19 Nov 2014 16:03:57 -0000
vti_backlinkinfo:VX|X001Z002F.asp
vti_nexttolasttimemodified:TW|25 Jul 2014 16:10:24 -0000
vti_cacheddtm:TX|19 Nov 2014 16:03:57 -0000
vti_filesize:IR|7815
vti_cachedtitle:SR|.:Web Site - :.
vti_cachedbodystyle:SR|<body onBeforeUnload="loadOut()"  leftmargin=0 topmargin=0 marginheight="0" marginwidth="0" bgcolor="#ffffff" onload=";" scroll="no" >
vti_cachedlinkinfo:VX|H|../favicon.ico D|Salir.asp S|<%=wURI%> S|images/user.jpg H|X001A001.asp H|X001A005.asp H|X001A004.asp H|X001A005.asp H|X001A006.asp H|X001X003.asp H|X001X004.asp H|X001X005.asp H|X001X001.asp H|X001X002.asp H|X001X108.asp
vti_cachedsvcrellinks:VX|NHUS|file:///D:/SRC/P131/InsysWeb/favicon.ico FDUS|Salir.asp USUS|<%=wURI%> FSUS|images/user.jpg FHUS|X001A001.asp FHUS|X001A005.asp FHUS|X001A004.asp FHUS|X001A005.asp FHUS|X001A006.asp FHUS|X001X003.asp FHUS|X001X004.asp FHUS|X001X005.asp FHUS|X001X001.asp FHUS|X001X002.asp FHUS|X001X108.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Window-target _top
vti_charset:SR|windows-1252
