vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|11 Dec 2009 22:03:42 -0000
vti_extenderversion:SR|6.0.2.5516
vti_author:SR|ESTBMAS001\\EPAREDES
vti_modifiedby:SR|SERVER003\\Administrator
vti_timecreated:TR|03 Jul 2005 16:14:40 -0000
vti_title:SR|Actualizar Noticias del Web Site de Carvica
vti_timelastindexed:TW|11 Dec 2009 22:03:42 -0000
vti_backlinkinfo:VX|adm/X010Z300F.asp
vti_cacheddtm:TX|11 Dec 2009 22:03:42 -0000
vti_filesize:IR|1372
vti_cachedtitle:SR|Actualizar Noticias del Web Site de Carvica
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|F|<%=wURLH%> F|<%=wURLD%> F|<%=wURLP%>
vti_cachedsvcrellinks:VX|UFUS|<%=wURLH%> UFUS|<%=wURLD%> UFUS|<%=wURLP%>
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=windows-1252 GENERATOR Microsoft\\ FrontPage\\ 4.0 ProgId FrontPage.Editor.Document
vti_charset:SR|windows-1252
vti_progid:SR|FrontPage.Editor.Document
vti_generator:SR|Microsoft FrontPage 4.0
vti_hasframeset:BR|true
